// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC43gQ3x_NO4Rr-k4pUERRilm9RySkyfz8',
    appId: '1:254729600009:web:122b5d3d09d90fcbda8cd8',
    messagingSenderId: '254729600009',
    projectId: 'flutter-chat-f7e29',
    authDomain: 'flutter-chat-f7e29.firebaseapp.com',
    storageBucket: 'flutter-chat-f7e29.appspot.com',
    measurementId: 'G-MLWKV3CCBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVP26KYTtT79usimTjoyjcEH5SbJA8Ha0',
    appId: '1:254729600009:android:da47fc0b8a751f8dda8cd8',
    messagingSenderId: '254729600009',
    projectId: 'flutter-chat-f7e29',
    storageBucket: 'flutter-chat-f7e29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvgQKE9jFsXHXmPJ8PyVcbmnap39wQKFg',
    appId: '1:254729600009:ios:d24e3654e087b348da8cd8',
    messagingSenderId: '254729600009',
    projectId: 'flutter-chat-f7e29',
    storageBucket: 'flutter-chat-f7e29.appspot.com',
    iosClientId: '254729600009-1o5lg07o5p5cpuupf5t7p5u88is4spnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvgQKE9jFsXHXmPJ8PyVcbmnap39wQKFg',
    appId: '1:254729600009:ios:d24e3654e087b348da8cd8',
    messagingSenderId: '254729600009',
    projectId: 'flutter-chat-f7e29',
    storageBucket: 'flutter-chat-f7e29.appspot.com',
    iosClientId: '254729600009-1o5lg07o5p5cpuupf5t7p5u88is4spnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
